import React, {useState} from 'react';
import {
  View,
  Text,
  Modal,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import RNPickerSelect from 'react-native-picker-select';
import * as DocumentPicker from 'expo-document-picker';
import { transcribeAudio } from '@/lib/api/audio';
import { generateAINote } from '@/lib/api/notes';

// Local emoji icon fallback (keeps component dependency-free)
const Icon: React.FC<{name: string; size?: number; color?: string; style?: any}> = ({
  name,
  size = 18,
  color = '#000',
  style,
}) => {
  const map: Record<string, string> = {
    close: '✕',
    upload: '⤴️',
    folder: '📁',
    caret: '▾',
    sparkle: '✨',
  };
  const glyph = map[name] ?? '◻️';
  return <Text style={[{fontSize: size, color}, style]}>{glyph}</Text>;
};

type Props = {
  visible?: boolean;
  onClose?: () => void;
  inline?: boolean;
  onNoteGenerated?: (noteId: string) => void;
};

const UploadAudio: React.FC<Props> = ({visible: visibleProp, onClose, inline = false, onNoteGenerated}) => {
  const [internalVisible, setInternalVisible] = useState<boolean>(visibleProp ?? true);
  const visible = typeof visibleProp === 'boolean' ? visibleProp : internalVisible;
  const [language, setLanguage] = useState('english');
  const [folder, setFolder] = useState('all_notes');
  const [selectedFile, setSelectedFile] = useState<DocumentPicker.DocumentPickerAsset | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState<'transcribing' | 'generating' | null>(null);

  const close = () => {
    if (onClose) onClose();
    else setInternalVisible(false);
  };

  const pickAudioFile = async () => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: 'audio/*',
        copyToCacheDirectory: true,
      });

      if (!result.canceled && result.assets && result.assets.length > 0) {
        const file = result.assets[0];
        setSelectedFile(file);
        console.log('Selected audio file:', file);
      }
    } catch (error) {
      console.error('Error picking audio file:', error);
      Alert.alert('Error', 'Failed to pick audio file. Please try again.');
    }
  };

  const handleGenerateNotes = async () => {
    if (!selectedFile) {
      Alert.alert('No File Selected', 'Please select an audio file first.');
      return;
    }

    setIsProcessing(true);
    
    try {
      // Step 1: Transcribe audio and generate notes
      setProcessingStep('transcribing');
      console.log('Starting audio transcription and note generation...');
      
      // Create FormData for audio file
      const formData = new FormData();
      formData.append('audio', {
        uri: selectedFile.uri,
        type: selectedFile.mimeType || 'audio/mpeg',
        name: selectedFile.name,
      } as any);

      const transcriptionResult = await transcribeAudio(formData);
      console.log('Transcription completed:', transcriptionResult);

      // Check if note was already generated by the backend
      let note;
      if (transcriptionResult.note && transcriptionResult.note.id) {
        console.log('Note was generated by backend:', transcriptionResult.note);
        note = transcriptionResult.note;
      } else {
        // Fallback: Generate AI note from transcript if not already done
        setProcessingStep('generating');
        console.log('Generating AI note from transcript...');
        
        note = await generateAINote({
          transcriptId: transcriptionResult.transcript.id,
        });
        
        console.log('Note generated successfully:', note);
      }

      // Success!
      Alert.alert(
        'Success!',
        'Your notes have been generated successfully.',
        [
          {
            text: 'View Notes',
            onPress: () => {
              if (onNoteGenerated) {
                onNoteGenerated(note.id);
              }
              close();
            },
          },
          {
            text: 'Close',
            onPress: close,
            style: 'cancel',
          },
        ]
      );
    } catch (error: any) {
      console.error('Error processing audio:', error);
      
      // Provide more specific error messages
      let errorMessage = 'Failed to process audio file. Please try again.';
      
      if (error?.message) {
        if (error.message.includes('timeout') || error.message.includes('Network Error')) {
          errorMessage = 'The request took too long. Your audio may still be processing. Please check your notes in a moment.';
        } else if (error.message.includes('401') || error.message.includes('Authentication')) {
          errorMessage = 'Authentication required. Please sign in again.';
        } else if (error.message.includes('413') || error.message.includes('too large')) {
          errorMessage = 'Audio file is too large. Maximum size is 25MB.';
        } else if (error.message.includes('Unsupported')) {
          errorMessage = 'Unsupported audio format. Please use MP3, WAV, or M4A.';
        } else {
          errorMessage = error.message;
        }
      }
      
      Alert.alert('Processing Error', errorMessage);
    } finally {
      setIsProcessing(false);
      setProcessingStep(null);
    }
  };

  const inner = (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Upload audio</Text>
        <TouchableOpacity onPress={close}>
          <Icon name="close" size={22} color="#111" />
        </TouchableOpacity>
      </View>

      <TouchableOpacity style={styles.uploadArea} onPress={pickAudioFile} activeOpacity={0.7}>
        <Icon name="upload" size={44} color="#6b6b6b" />
        <Text style={styles.uploadText}>
          {selectedFile ? selectedFile.name : 'Drag audio file here, or click to select'}
        </Text>
        {selectedFile && (
          <Text style={styles.fileInfo}>
            {(selectedFile.size! / 1024 / 1024).toFixed(2)} MB
          </Text>
        )}
      </TouchableOpacity>

      <View style={styles.row}>
        <View style={styles.pickerWrap}>
          <Text style={styles.label}>Audio language</Text>
          <RNPickerSelect
            onValueChange={val => setLanguage(val)}
            items={[{label: 'English', value: 'english'}]}
            value={language}
            style={pickerStyles}
            useNativeAndroidPickerStyle={false}
            placeholder={{}}
            Icon={() => <Icon name="caret" size={16} color="#6b6b6b" />}
          />
        </View>

        <View style={styles.pickerWrap}>
          <Text style={styles.label}>Folder</Text>
          <View style={styles.folderRow}>
            <View style={styles.folderIconWrap}>
              <Icon name="folder" size={14} color="#7b61ff" />
            </View>
            <RNPickerSelect
              onValueChange={val => setFolder(val)}
              items={[{label: 'All notes', value: 'all_notes'}]}
              value={folder}
              style={pickerStyles}
              useNativeAndroidPickerStyle={false}
              placeholder={{}}
              Icon={() => <Icon name="caret" size={16} color="#6b6b6b" />}
            />
          </View>
        </View>
      </View>

      <TouchableOpacity 
        style={[
          styles.generateBtn, 
          (isProcessing || !selectedFile) && styles.generateBtnDisabled
        ]} 
        activeOpacity={0.85} 
        onPress={handleGenerateNotes} 
        disabled={isProcessing || !selectedFile}
      >
        {isProcessing ? (
          <>
            <ActivityIndicator color="#fff" size="small" style={{marginRight: 8}} />
            <Text style={styles.generateText}>
              {processingStep === 'transcribing' ? 'Transcribing Audio...' : 'Generating Notes...'}
            </Text>
          </>
        ) : (
          <>
            <Icon name="sparkle" size={16} color="#fff" style={{marginRight: 8}} />
            <Text style={styles.generateText}>Generate Notes</Text>
          </>
        )}
      </TouchableOpacity>
    </View>
  );

  if (inline) return <View>{inner}</View>;

  return (
    <Modal visible={visible} transparent animationType="slide">
      <View style={styles.overlay}>
        <TouchableOpacity style={styles.backdrop} onPress={close} />
        <SafeAreaView style={{flex: 1}}>
          {inner}
        </SafeAreaView>
      </View>
    </Modal>
  );
};

export default UploadAudio;

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  container: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 10,
    paddingTop: 16,
    paddingBottom: 32,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  title: {color: '#111', fontSize: 18, fontWeight: '600'},
  uploadArea: {
    marginTop: 8,
    backgroundColor: '#fbfbfd',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e6e6ea',
    paddingVertical: 28,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadText: {color: '#6b6b6b', marginTop: 12},
  fileInfo: {color: '#6b6b6b', fontSize: 12, marginTop: 4},
  row: {flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginTop: 14},
  pickerWrap: {flex: 1, marginVertical: 8},
  label: {color: '#6b6b6b', fontSize: 12, marginBottom: 6},
  folderRow: {flexDirection: 'row', alignItems: 'center'},
  folderIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#f2efff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  generateBtn: {
    flexDirection: 'row',
    backgroundColor: '#000',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    marginTop: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
    justifyContent: 'center',
    opacity: 1,
  },
  generateBtnDisabled: {
    backgroundColor: '#999',
    opacity: 0.6,
  },
  generateText: {color: '#fff', fontWeight: '700'},
});

const pickerStyles = {
  inputIOS: {
    color: '#111',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
    fontSize: 14,
  },
  inputAndroid: {
    color: '#111',
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    fontSize: 14,
  },
  placeholder: {
    color: '#6b6b6b',
  },
};
