import React, {useState} from 'react';
import {
  View,
  Text,
  Modal,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  Alert,
  ActivityIndicator,
  Dimensions,
} from 'react-native';
import RNPickerSelect from 'react-native-picker-select';
import * as DocumentPicker from 'expo-document-picker';
import { Upload } from 'lucide-react-native';
import { transcribeAudio } from '@/lib/api/audio';
import { generateAINote } from '@/lib/api/notes';
import GenerateNote from '@/components/ui/GenerateNote';
import FolderSelect from '@/components/ui/FolderSelect';

// Local emoji icon fallback (keeps component dependency-free)
const Icon: React.FC<{name: string; size?: number; color?: string; style?: any}> = ({
  name,
  size = 18,
  color = '#000',
  style,
}) => {
  const map: Record<string, string> = {
    close: '✕',
    upload: '⤴️',
    folder: '📁',
    caret: '▾',
    sparkle: '✨',
  };
  const glyph = map[name] ?? '◻️';
  return <Text style={[{fontSize: size, color}, style]}>{glyph}</Text>;
};

type Props = {
  visible?: boolean;
  onClose?: () => void;
  inline?: boolean;
  onNoteGenerated?: (noteId: string) => void;
};

const UploadAudio: React.FC<Props> = ({visible: visibleProp, onClose, inline = false, onNoteGenerated}) => {
  const [internalVisible, setInternalVisible] = useState<boolean>(visibleProp ?? true);
  const visible = typeof visibleProp === 'boolean' ? visibleProp : internalVisible;
  const [language, setLanguage] = useState('english');
  const [folder, setFolder] = useState('all_notes');
  const [selectedFile, setSelectedFile] = useState<DocumentPicker.DocumentPickerAsset | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState<'transcribing' | 'generating' | null>(null);

  const close = () => {
    if (onClose) onClose();
    else setInternalVisible(false);
  };

  const pickAudioFile = async () => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: 'audio/*',
        copyToCacheDirectory: true,
      });

      if (!result.canceled && result.assets && result.assets.length > 0) {
        const file = result.assets[0];
        setSelectedFile(file);
        console.log('Selected audio file:', file);
      }
    } catch (error) {
      console.error('Error picking audio file:', error);
      Alert.alert('Error', 'Failed to pick audio file. Please try again.');
    }
  };

  const handleGenerateNotes = async () => {
    if (!selectedFile) {
      Alert.alert('No File Selected', 'Please select an audio file first.');
      return;
    }

    setIsProcessing(true);
    
    try {
      // Step 1: Transcribe audio and generate notes
      setProcessingStep('transcribing');
      console.log('Starting audio transcription and note generation...');
      
      // Create FormData for audio file
      const formData = new FormData();
      formData.append('audio', {
        uri: selectedFile.uri,
        type: selectedFile.mimeType || 'audio/mpeg',
        name: selectedFile.name,
      } as any);

      const transcriptionResult = await transcribeAudio(formData);
      console.log('Transcription completed:', transcriptionResult);

      // Check if note was already generated by the backend
      let note;
      if (transcriptionResult.note && transcriptionResult.note.id) {
        console.log('Note was generated by backend:', transcriptionResult.note);
        note = transcriptionResult.note;
      } else {
        // Fallback: Generate AI note from transcript if not already done
        setProcessingStep('generating');
        console.log('Generating AI note from transcript...');
        
        note = await generateAINote({
          transcriptId: transcriptionResult.transcript.id,
        });
        
        console.log('Note generated successfully:', note);
      }

      // Success!
      Alert.alert(
        'Success!',
        'Your notes have been generated successfully.',
        [
          {
            text: 'View Notes',
            onPress: () => {
              if (onNoteGenerated) {
                onNoteGenerated(note.id);
              }
              close();
            },
          },
          {
            text: 'Close',
            onPress: close,
            style: 'cancel',
          },
        ]
      );
    } catch (error: any) {
      console.error('Error processing audio:', error);
      
      // Provide more specific error messages
      let errorMessage = 'Failed to process audio file. Please try again.';
      
      if (error?.message) {
        if (error.message.includes('timeout') || error.message.includes('Network Error')) {
          errorMessage = 'The request took too long. Your audio may still be processing. Please check your notes in a moment.';
        } else if (error.message.includes('401') || error.message.includes('Authentication')) {
          errorMessage = 'Authentication required. Please sign in again.';
        } else if (error.message.includes('413') || error.message.includes('too large')) {
          errorMessage = 'Audio file is too large. Maximum size is 25MB.';
        } else if (error.message.includes('Unsupported')) {
          errorMessage = 'Unsupported audio format. Please use MP3, WAV, or M4A.';
        } else {
          errorMessage = error.message;
        }
      }
      
      Alert.alert('Processing Error', errorMessage);
    } finally {
      setIsProcessing(false);
      setProcessingStep(null);
    }
  };

  const inner = (
    <>
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Upload audio</Text>
          <TouchableOpacity onPress={close}>
            <Icon name="close" size={22} color="#111" />
          </TouchableOpacity>
        </View>
      </View>
      <View style={styles.separator} />
      <View style={[styles.container, styles.containerContent]}>
        <TouchableOpacity style={styles.uploadArea} onPress={pickAudioFile} activeOpacity={0.7}>
        <Upload size={44} color="#6b6b6b" />
        <Text style={styles.uploadText}>
          {selectedFile ? selectedFile.name : 'Drag audio file here, or click to select'}
        </Text>
        {selectedFile && (
          <Text style={styles.fileInfo}>
            {(selectedFile.size! / 1024 / 1024).toFixed(2)} MB
          </Text>
        )}
      </TouchableOpacity>

      <View style={styles.pickerWrap}>
        <Text style={styles.label}>Audio language</Text>
        <RNPickerSelect
          onValueChange={val => setLanguage(val)}
          items={[{label: 'English', value: 'english'}]}
          value={language}
          style={pickerStyles}
          useNativeAndroidPickerStyle={false}
          placeholder={{}}
          Icon={() => <Icon name="caret" size={16} color="#6b6b6b" />}
        />
      </View>

      <FolderSelect
        value={folder}
        onValueChange={(val: string) => setFolder(val)}
        options={[{label: 'All notes', value: 'all_notes'}]}
      />

        <GenerateNote
          onPress={handleGenerateNotes}
          disabled={!selectedFile}
          loading={isProcessing}
          loadingText={processingStep === 'transcribing' ? 'Transcribing Audio...' : 'Generating Notes...'}
          buttonText="Generate Notes"
          style={styles.customGenerateBtn}
          textStyle={styles.customGenerateText}
        />
      </View>
    </>
  );

  if (inline) return <View>{inner}</View>;

  return (
    <Modal visible={visible} transparent animationType="slide">
      <View style={styles.overlay}>
        <TouchableOpacity style={styles.backdrop} onPress={close} />
        <SafeAreaView style={{flex: 1}}>
          {inner}
        </SafeAreaView>
      </View>
    </Modal>
  );
};

export default UploadAudio;

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  container: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 10,
    paddingTop: 16,
    paddingBottom: 16,
  },
  containerContent: {
    paddingTop: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 7,
    marginHorizontal: 8,
  },
  title: {color: '#111', fontSize: 18, fontWeight: '600'},
  separator: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginHorizontal: -40,
    width: Dimensions.get('window').width,
  },
  uploadArea: {
    marginTop: 8,
    backgroundColor: '#fbfbfd',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e6e6ea',
    paddingVertical: 40,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadText: {color: '#6b6b6b', marginTop: 12},
  fileInfo: {color: '#6b6b6b', fontSize: 12, marginTop: 4},
  row: {flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginTop: 14},
  pickerWrap: {marginVertical: 8, marginHorizontal: 8},
  label: {
    color: '#6b6b6b',
    fontSize: 12,
    marginBottom: 6,
    height: 24,
    borderRadius: 0,
    alignSelf: 'stretch',
  },
  folderRow: {flexDirection: 'row', alignItems: 'center'},
  folderIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#f2efff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  customGenerateBtn: {
    width: 300,
    height: 56,
    borderRadius: 15,
    marginTop: 18,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  customGenerateText: {
    fontFamily: 'Arimo',
    fontSize: 19,
    lineHeight: 28,
  },
});

const pickerStyles = {
  inputIOS: {
    color: '#111',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    fontSize: 14,
    borderWidth: 1.26,
    borderColor: '#D4D4D4',
    height: 53,
  },
  inputAndroid: {
    color: '#111',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    fontSize: 14,
    borderWidth: 1.26,
    borderColor: '#D4D4D4',
    height: 53,
  },
  placeholder: {
    color: '#6b6b6b',
  },
  iconContainer: {
    top: 16,
    right: 16,
  },
};
