import React, {useState} from 'react';
import {
  View,
  Text,
  Modal,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  TextInput,
  Alert,
  ActivityIndicator,
} from 'react-native';
import RNPickerSelect from 'react-native-picker-select';
import { processWebpage } from '@/lib/api/webpage';
import { generateAINote } from '@/lib/api/notes';

// Prefer react-native-vector-icons when available; fallback to emoji glyphs so component is resilient
let Icon: any = null;
try {
  // eslint-disable-next-line global-require
  Icon = require('react-native-vector-icons/MaterialCommunityIcons').default;
} catch (e) {
  Icon = ({name, size = 18, color = '#000', style}: any) => {
    const map: Record<string, string> = {
      close: '✕',
      'chevron-down': '▾',
      sparkle: '✨',
      person: '👤',
    };
    const glyph = map[name] ?? '◻️';
    return <Text style={[{fontSize: size, color}, style]}>{glyph}</Text>;
  };
}

type Props = {
  visible?: boolean;
  onClose?: () => void;
  inline?: boolean;
  onNoteGenerated?: (noteId: string) => void;
};

const WebLink: React.FC<Props> = ({visible: visibleProp, onClose, inline = false, onNoteGenerated}) => {
  const [internalVisible, setInternalVisible] = useState<boolean>(visibleProp ?? true);
  const visible = typeof visibleProp === 'boolean' ? visibleProp : internalVisible;
  const [link, setLink] = useState('');
  const [folder, setFolder] = useState('all_notes');
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState<'extracting' | 'generating' | null>(null);

  const close = () => {
    if (onClose) onClose();
    else setInternalVisible(false);
  };

  const isValidUrl = (url: string): boolean => {
    try {
      // Add protocol if missing
      const urlToTest = url.startsWith('http') ? url : `https://${url}`;
      new URL(urlToTest);
      return true;
    } catch {
      return false;
    }
  };

  const handleGenerateNotes = async () => {
    if (!link.trim()) {
      Alert.alert('Link Required', 'Please enter a website URL or YouTube link.');
      return;
    }

    if (!isValidUrl(link.trim())) {
      Alert.alert('Invalid URL', 'Please enter a valid URL (e.g., youtube.com/watch?v=...)');
      return;
    }

    setIsProcessing(true);

    try {
      // Step 1: Process webpage/YouTube to extract content
      setProcessingStep('extracting');
      console.log('Processing webpage:', link);

      // Ensure URL has protocol
      const url = link.trim().startsWith('http') ? link.trim() : `https://${link.trim()}`;

      const webpageResult = await processWebpage({ url });
      console.log('Webpage processed:', webpageResult);

      // Check if note was already generated by the backend
      let note;
      if (webpageResult.note && webpageResult.note.id) {
        console.log('Note was generated by backend:', webpageResult.note);
        note = webpageResult.note;
      } else {
        // Step 2: Generate AI note from transcript
        setProcessingStep('generating');
        console.log('Generating AI note from transcript...');

        note = await generateAINote({
          transcriptId: webpageResult.transcript.id,
        });

        console.log('Note generated successfully:', note);
      }

      // Success!
      Alert.alert(
        'Success!',
        'Your notes have been generated successfully.',
        [
          {
            text: 'View Notes',
            onPress: () => {
              if (onNoteGenerated) {
                onNoteGenerated(note.id);
              }
              close();
            },
          },
          {
            text: 'Close',
            onPress: close,
            style: 'cancel',
          },
        ]
      );

      // Reset form
      setLink('');
    } catch (error: any) {
      console.error('Error processing webpage:', error);

      // Provide more specific error messages
      let errorMessage = 'Failed to process the link. Please try again.';

      if (error?.message) {
        if (error.message.includes('timeout') || error.message.includes('Network Error')) {
          errorMessage = 'The request took too long. Your content may still be processing. Please check your notes in a moment.';
        } else if (error.message.includes('401') || error.message.includes('Authentication')) {
          errorMessage = 'Authentication required. Please sign in again.';
        } else if (error.message.includes('Invalid URL') || error.message.includes('404')) {
          errorMessage = 'Unable to access the URL. Please check the link and try again.';
        } else if (error.message.includes('Failed to extract')) {
          errorMessage = 'Unable to extract content from this page. The page may require authentication or block automated access.';
        } else {
          errorMessage = error.message;
        }
      }

      Alert.alert('Processing Error', errorMessage);
    } finally {
      setIsProcessing(false);
      setProcessingStep(null);
    }
  };

  const inner = (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Add link</Text>
        <TouchableOpacity onPress={close}>
          <Icon name="close" size={20} color="#111" />
        </TouchableOpacity>
      </View>

      <View style={styles.field}>
        <Text style={styles.label}>Link</Text>
        <TextInput
          style={styles.input}
          placeholder="youtube.com/anyvideo"
          placeholderTextColor="#8b8b8b"
          value={link}
          onChangeText={setLink}
          autoCapitalize="none"
          keyboardType="url"
        />
        <Text style={styles.helper}>Also works with YouTube, PDFs, TikTok, Websites.</Text>
      </View>

      <View style={[styles.field, {marginTop: 10}]}>
        <Text style={styles.label}>Folder</Text>
        <View style={styles.folderRow}>
          <View style={styles.folderIconWrap}>
            <Icon name="account" size={14} color="#7b61ff" />
          </View>

          <RNPickerSelect
            onValueChange={val => setFolder(val)}
            items={[{label: 'All notes', value: 'all_notes'}]}
            value={folder}
            style={pickerStyles}
            useNativeAndroidPickerStyle={false}
            placeholder={{}}
            Icon={() => <Icon name="chevron-down" size={18} color="#6b6b6b" />}
          />
        </View>
      </View>

      <TouchableOpacity 
        style={[
          styles.generateBtn,
          (isProcessing || !link.trim()) && styles.generateBtnDisabled
        ]} 
        activeOpacity={0.85}
        onPress={handleGenerateNotes}
        disabled={isProcessing || !link.trim()}
      >
        {isProcessing ? (
          <>
            <ActivityIndicator color="#fff" size="small" style={{marginRight: 8}} />
            <Text style={styles.generateText}>
              {processingStep === 'extracting' ? 'Extracting Content...' : 'Generating Notes...'}
            </Text>
          </>
        ) : (
          <>
            <Icon name="sparkles" size={16} color="#fff" style={{marginRight: 8}} />
            <Text style={styles.generateText}>Generate Notes</Text>
          </>
        )}
      </TouchableOpacity>
    </View>
  );

  if (inline) return <View>{inner}</View>;

  return (
    <Modal visible={visible} transparent animationType="slide">
      <View style={styles.overlay}>
        <TouchableOpacity style={styles.backdrop} onPress={close} />
        <SafeAreaView style={{flex: 1}}>
          {inner}
        </SafeAreaView>
      </View>
    </Modal>
  );
};

export default WebLink;

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  container: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  title: {color: '#111', fontSize: 18, fontWeight: '600'},
  field: {marginTop: 8},
  label: {color: '#6b6b6b', fontSize: 12, marginBottom: 6},
  input: {
    backgroundColor: '#fbfbfd',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e6e6ea',
    paddingVertical: 12,
    paddingHorizontal: 12,
    color: '#111',
  },
  helper: {color: '#8b8b8b', fontSize: 12, marginTop: 8},
  folderRow: {flexDirection: 'row', alignItems: 'center'},
  folderIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#f2efff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  generateBtn: {
    flexDirection: 'row',
    backgroundColor: '#000',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    marginTop: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
    justifyContent: 'center',
  },
  generateBtnDisabled: {
    backgroundColor: '#999',
    opacity: 0.6,
  },
  generateText: {color: '#fff', fontWeight: '700'},
});

const pickerStyles = {
  inputIOS: {
    color: '#111',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
    fontSize: 14,
  },
  inputAndroid: {
    color: '#111',
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    fontSize: 14,
  },
  placeholder: {
    color: '#6b6b6b',
  },
};
