import React, { useState } from 'react';
import {
  View,
  Text,
  Modal,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  TextInput,
  Alert,
  ActivityIndicator,
  Dimensions,
} from 'react-native';
import RNPickerSelect from 'react-native-picker-select';
import { useNoteCreation } from '@/lib/hooks/useNoteCreation';
import GenerateNote from '@/components/ui/GenerateNote';
import FolderSelect from '@/components/ui/FolderSelect';

// Prefer react-native-vector-icons when available; fallback to emoji glyphs so component is resilient
let Icon: any = null;
try {
  // eslint-disable-next-line global-require
  Icon = require('react-native-vector-icons/MaterialCommunityIcons').default;
} catch (e) {
  Icon = ({ name, size = 18, color = '#000', style }: any) => {
    const map: Record<string, string> = {
      close: '✕',
      'chevron-down': '▾',
      sparkle: '✨',
      person: '👤',
    };
    const glyph = map[name] ?? '◻️';
    return <Text style={[{ fontSize: size, color }, style]}>{glyph}</Text>;
  };
}

type Props = {
  visible?: boolean;
  onClose?: () => void;
  inline?: boolean;
  onNoteGenerated?: (noteId: string) => void;
};

const WebLink: React.FC<Props> = ({ visible: visibleProp, onClose, inline = false, onNoteGenerated }) => {
  const { processWebpage, generateAINote } = useNoteCreation();
  const [internalVisible, setInternalVisible] = useState<boolean>(visibleProp ?? true);
  const visible = typeof visibleProp === 'boolean' ? visibleProp : internalVisible;
  const [link, setLink] = useState('');
  const [folder, setFolder] = useState('all_notes');
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState<'extracting' | 'generating' | null>(null);

  const close = () => {
    if (onClose) onClose();
    else setInternalVisible(false);
  };

  const isValidUrl = (url: string): boolean => {
    try {
      // Add protocol if missing
      const urlToTest = url.startsWith('http') ? url : `https://${url}`;
      new URL(urlToTest);
      return true;
    } catch {
      return false;
    }
  };

  const handleGenerateNotes = async () => {
    if (!link.trim()) {
      Alert.alert('Link Required', 'Please enter a website URL or YouTube link.');
      return;
    }

    if (!isValidUrl(link.trim())) {
      Alert.alert('Invalid URL', 'Please enter a valid URL (e.g., youtube.com/watch?v=...)');
      return;
    }

    setIsProcessing(true);

    try {
      // Step 1: Process webpage/YouTube to extract content
      setProcessingStep('extracting');
      console.log('Processing webpage:', link);

      // Ensure URL has protocol
      const url = link.trim().startsWith('http') ? link.trim() : `https://${link.trim()}`;

      // Use hook for webpage processing
      const webpageResult = await processWebpage({ url });

      if (!webpageResult) {
        // Error handled by hook
        return;
      }

      console.log('Webpage processed:', webpageResult);

      // Check if note was already generated by the backend
      let note;
      if (webpageResult.note && webpageResult.note.id) {
        console.log('Note was generated by backend:', webpageResult.note);
        note = webpageResult.note;
      } else {
        // Step 2: Generate AI note from transcript
        setProcessingStep('generating');
        console.log('Generating AI note from transcript...');

        // Use hook for note generation
        note = await generateAINote({
          transcriptId: webpageResult.transcript.id,
        });

        if (!note) {
          // Error handled by hook
          return;
        }

        console.log('Note generated successfully:', note);
      }

      // Success!
      Alert.alert(
        'Success!',
        'Your notes have been generated successfully.',
        [
          {
            text: 'View Notes',
            onPress: () => {
              if (onNoteGenerated) {
                onNoteGenerated(note.id);
              }
              close();
            },
          },
          {
            text: 'Close',
            onPress: close,
            style: 'cancel',
          },
        ]
      );

      // Reset form
      setLink('');
    } catch (error: any) {
      console.error('Error processing webpage:', error);
      // Hook handles errors, but just in case
    } finally {
      setIsProcessing(false);
      setProcessingStep(null);
    }
  };

  const inner = (
    <>
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Add link</Text>
          <TouchableOpacity onPress={close}>
            <Icon name="close" size={20} color="#111" />
          </TouchableOpacity>
        </View>
      </View>
      <View style={styles.separator} />
      <View style={[styles.container, styles.containerContent]}>
        <View style={styles.field}>
          <Text style={styles.label}>Link</Text>
          <TextInput
            style={styles.input}
            placeholder="youtube.com/anyvideo"
            placeholderTextColor="#8b8b8b"
            value={link}
            onChangeText={setLink}
            autoCapitalize="none"
            keyboardType="url"
          />
          <Text style={styles.helper}>Also works with YouTube, PDFs, TikTok, Websites.</Text>
        </View>

        <FolderSelect
          value={folder}
          onValueChange={(val: string) => setFolder(val)}
          options={[{ label: 'All notes', value: 'all_notes' }]}
          style={{ marginTop: 10 }}
        />

        <GenerateNote
          onPress={handleGenerateNotes}
          disabled={!link.trim()}
          loading={isProcessing}
          loadingText={processingStep === 'extracting' ? 'Extracting Content...' : 'Generating Notes...'}
          buttonText="Generate Notes"
          style={styles.customGenerateBtn}
          textStyle={styles.customGenerateText}
        />
      </View>
    </>
  );

  if (inline) return <View>{inner}</View>;

  return (
    <Modal visible={visible} transparent animationType="slide">
      <View style={styles.overlay}>
        <TouchableOpacity style={styles.backdrop} onPress={close} />
        <SafeAreaView style={{ flex: 1 }}>
          {inner}
        </SafeAreaView>
      </View>
    </Modal>
  );
};

export default WebLink;

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  container: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 10,
    paddingBottom: 16,
  },
  containerContent: {
    paddingTop: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 7,
    marginHorizontal: 8,
  },
  title: { color: '#111', fontSize: 20, fontWeight: '600' },
  separator: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginHorizontal: -40,
    width: Dimensions.get('window').width + 20,
  },
  field: { marginTop: 8 },
  label: {
    fontFamily: 'Arimo',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 32,
    color: '#364153',
    marginBottom: 6,
  },
  input: {
    color: '#111',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    fontSize: 14,
    borderWidth: 1.26,
    borderColor: '#D4D4D4',
    height: 53,
  },
  helper: { color: '#8b8b8b', fontSize: 12, marginTop: 8 },
  folderRow: { flexDirection: 'row', alignItems: 'center' },
  folderIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#f2efff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  customGenerateBtn: {
    width: 300,
    height: 56,
    borderRadius: 15,
    marginTop: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  customGenerateText: {
    fontFamily: 'Arimo',
    fontSize: 19,
    lineHeight: 28,
  },
});

const pickerStyles = {
  inputIOS: {
    color: '#111',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    fontSize: 14,
    borderWidth: 1.26,
    borderColor: '#D4D4D4',
    height: 53,
  },
  inputAndroid: {
    color: '#111',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    fontSize: 14,
    borderWidth: 1.26,
    borderColor: '#D4D4D4',
    height: 53,
  },
  placeholder: {
    color: '#6b6b6b',
  },
  iconContainer: {
    top: 16,
    right: 16,
  },
};