import React, { useState } from 'react';
import {
  View,
  Text,
  Modal,
  Pressable,
  StyleSheet,
  SafeAreaView,
  TextInput,
} from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useNoteCreation } from '@/lib/hooks/useNoteCreation';
import FullWidthButton from '@/components/ui/FullWidthButton';
import FolderSelect from '@/components/ui/FolderSelect';
import { useAlert } from '@/lib/contexts/AlertContext';
import { useTheme } from '@/lib/hooks/useTheme';

type Props = {
  visible?: boolean;
  onClose?: () => void;
  inline?: boolean;
  onNoteGenerated?: (noteId: string) => void;
};

const WebLink: React.FC<Props> = ({ visible: visibleProp, onClose, inline = false, onNoteGenerated }) => {
  const { processWebpage, processYouTube, generateAINote } = useNoteCreation();
  const [internalVisible, setInternalVisible] = useState<boolean>(visibleProp ?? true);
  const { showAlert } = useAlert();
  const { theme, mode } = useTheme();
  const c = theme.colors;
  const isDark = mode === 'dark';
  const inputBg = isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.03)';
  const visible = typeof visibleProp === 'boolean' ? visibleProp : internalVisible;
  const [link, setLink] = useState('');
  const [folder, setFolder] = useState('');  // Empty string = no folder (uncategorized)
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState<'extracting' | 'generating' | null>(null);

  const close = () => {
    if (onClose) onClose();
    else setInternalVisible(false);
  };

  const isValidUrl = (url: string): boolean => {
    try {
      // Add protocol if missing
      const urlToTest = url.startsWith('http') ? url : `https://${url}`;
      new URL(urlToTest);
      return true;
    } catch {
      return false;
    }
  };

  /**
   * Check if the URL is a YouTube URL
   */
  const isYouTubeUrl = (url: string): boolean => {
    const youtubeRegex = /^(https?:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/|youtube\.com\/shorts\/)/i;
    return youtubeRegex.test(url);
  };

  const handleGenerateNotes = async () => {
    if (!link.trim()) {
      showAlert('Link Required', 'Please enter a website URL or YouTube link.');
      return;
    }

    if (!isValidUrl(link.trim())) {
      showAlert('Invalid URL', 'Please enter a valid URL (e.g., youtube.com/watch?v=...)');
      return;
    }

    setIsProcessing(true);

    try {
      // Step 1: Process webpage/YouTube to extract content
      setProcessingStep('extracting');

      // Ensure URL has protocol
      const url = link.trim().startsWith('http') ? link.trim() : `https://${link.trim()}`;

      // Detect if it's a YouTube URL
      const isYouTube = isYouTubeUrl(url);

      let result: { transcript: { id: string; content?: string }; note?: { id: string; title: string } | null };

      if (isYouTube) {
        // Use YouTube API for YouTube URLs
        const youtubeResult = await processYouTube({ url, folderId: folder || undefined });

        if (!youtubeResult) {
          return;
        }

        // ProcessYouTubeResponse is a Transcript directly (backend returns data: transcript)
        result = {
          transcript: youtubeResult,
          note: null, // YouTube API only returns transcript, note needs to be generated separately
        };
      } else {
        // Use Webpage API for other URLs
        const webpageResult = await processWebpage({ url, folderId: folder || undefined });

        if (!webpageResult) {
          return;
        }

        result = webpageResult;
      }

      // Check if note was already generated by the backend
      let note;
      if (result.note && result.note.id) {
        note = result.note;
      } else {
        // Step 2: Generate AI note from transcript
        setProcessingStep('generating');

        // Use hook for note generation
        note = await generateAINote({
          transcriptId: result.transcript.id,
          folderId: folder || undefined,
        });

        if (!note) {
          return;
        }
      }

      // Trigger refresh callback immediately on success
      if (onNoteGenerated) {
        onNoteGenerated(note.id);
      }

      // Success!
      showAlert(
        'Success!',
        'Your notes have been generated successfully.',
        [
          {
            text: 'View Notes',
            onPress: () => {
              close();
            },
          },
          {
            text: 'Close',
            onPress: close,
            style: 'cancel',
          },
        ]
      );

      // Reset form
      setLink('');
    } catch (error: any) {
      // Hook handles errors
    } finally {
      setIsProcessing(false);
      setProcessingStep(null);
    }
  };

  const styles = StyleSheet.create({
    overlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: isDark ? 'rgba(0,0,0,0.7)' : 'rgba(0,0,0,0.4)',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    container: {
      backgroundColor: c.card,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: 12,
      marginBottom: 4,
    },
    title: { color: c.foreground, fontSize: 20, fontWeight: '600' },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: inputBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    field: { marginTop: 12 },
    label: {
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      color: c.mutedForeground,
      marginBottom: 8,
      textTransform: 'uppercase',
    },
    input: {
      color: c.foreground,
      paddingVertical: 14,
      paddingHorizontal: 16,
      backgroundColor: inputBg,
      borderRadius: 12,
      fontSize: 14,
      height: 48,
    },
    helper: {
      color: c.mutedForeground,
      fontSize: 11,
      marginTop: 8,
      opacity: 0.7,
    },
    buttonContainer: {},
  });

  const inner = (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Add link</Text>
        <Pressable onPress={close} style={styles.closeButton}>
          <Feather name="x" size={18} color={c.foreground} />
        </Pressable>
      </View>

      <View style={styles.field}>
        <Text style={styles.label}>LINK</Text>
        <TextInput
          style={styles.input}
          placeholder="youtube.com/anyvideo"
          placeholderTextColor={c.mutedForeground}
          value={link}
          onChangeText={setLink}
          autoCapitalize="none"
          keyboardType="url"
        />
        <Text style={styles.helper}>Also works with YouTube, PDFs, TikTok, Websites.</Text>
      </View>

      <FolderSelect
        value={folder}
        onValueChange={(val: string) => setFolder(val)}
        style={{ marginTop: 12 }}
      />

      <View style={styles.buttonContainer}>
        <FullWidthButton
          onPress={handleGenerateNotes}
          disabled={!link.trim()}
          loading={isProcessing}
          loadingText={processingStep === 'extracting' ? 'Extracting Content...' : 'Generating Notes...'}
          buttonText="Generate Notes"
        />
      </View>
    </View>
  );

  if (inline) return <View>{inner}</View>;

  return (
    <Modal visible={visible} transparent animationType="slide">
      <View style={styles.overlay}>
        <Pressable style={styles.backdrop} onPress={close} />
        <SafeAreaView style={{ flex: 1 }}>
          {inner}
        </SafeAreaView>
      </View>
    </Modal>
  );
};

export default WebLink;
