import { StyleSheet, Platform } from 'react-native'

const PURPLE = '#7C3AED'
const BG = '#FFFFFF'

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  statusBar: {
    height: Platform.OS === 'ios' ? 44 : 28,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeWrap: { backgroundColor: '#FF4D4F', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  time: { color: '#fff', fontWeight: '700', fontFamily: 'Arimo', fontSize: 13 },
  statusIcons: { flexDirection: 'row' },
  icon: { marginLeft: 8, fontSize: 14 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 60 },
  progressWrap: { flex: 1, paddingRight: 16 },
  progressTrack: { height: 6, backgroundColor: '#EEE8FF', borderRadius: 6, overflow: 'hidden' },
  progressFill: { width: '100%', height: '100%', backgroundColor: PURPLE },
  content: { paddingHorizontal: 20, paddingTop: 54, flex: 1, alignItems: 'center' },
  mainTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: '#9810FA',
    textAlign: 'center',
    fontFamily: 'Arimo',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 20,
    lineHeight: 30,
    fontWeight: '700',
    color: '#9810FA',
    textAlign: 'center',
    fontFamily: 'Arimo',
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: '#1E2939',
    textAlign: 'center',
    fontFamily: 'Arimo',
    marginBottom: 32,
    paddingHorizontal: 60,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingTop: 23.99,
    paddingHorizontal: 23.99,
    paddingBottom: 0,
    width: 329,
    height: 291.96,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 23.99,
    height: 27.99,
  },
  cardTitle: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '400',
    color: '#000000',
    fontFamily: 'Arimo',
  },
  badges: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgePurple: {
    backgroundColor: '#F3E8FF',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    height: 24,
    justifyContent: 'center',
    marginRight: 17,
  },
  badgePurpleText: {
    color: '#7C3AED',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Arimo',
  },
  badgeGrey: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: 'transparent',
    height: 20,
    justifyContent: 'center',
  },
  badgeGreyText: {
    color: '#4A5565',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Arimo',
  },
  chartContainer: { marginTop: 8 },
  footer: { paddingHorizontal: 25, paddingBottom: 40 },
  cta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 12 },
  ctaText: { color: '#fff', fontSize: 16, fontWeight: '700', marginRight: 8 },
  ctaArrow: { color: '#fff', fontSize: 18, fontWeight: '700' },
  leftGradient: { position: 'absolute', left: -40, top: 80, width: 220, height: 420, borderRadius: 220, backgroundColor: '#F5EEFF', opacity: 0.7, transform: [{ rotate: '-25deg' }] },
  homeIndicator: { height: 6, backgroundColor: '#E9E9EF', marginHorizontal: 110, borderRadius: 3, marginTop: 10, marginBottom: Platform.OS === 'ios' ? 24 : 8 },
})
