import { StyleSheet, Platform } from 'react-native'

const PURPLE = '#7C3AED'
const BG = '#FFFFFF'

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  statusBar: {
    height: Platform.OS === 'ios' ? 44 : 28,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeWrap: { backgroundColor: '#FF4D4F', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  time: { color: '#fff', fontWeight: '700', fontFamily: 'Arimo', fontSize: 13 },
  statusIcons: { flexDirection: 'row' },
  icon: { marginLeft: 8, fontSize: 14 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 60 },
  progressWrap: { flex: 1, paddingRight: 16 },
  progressTrack: { height: 6, backgroundColor: '#EEE8FF', borderRadius: 6, overflow: 'hidden' },
  progressFill: { width: '44.44%', height: '100%', backgroundColor: PURPLE },
  scrollContent: { flex: 1 },
  content: {
    paddingHorizontal: 24,
    paddingTop: 103.08,
    paddingBottom: 24,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 10,
    fontFamily: 'Arimo',
    lineHeight: 28,
    textAlign: 'center',
  },
  subtitle: {
    color: '#7C3AED',
    fontSize: 20,
    marginTop: 50,
    marginBottom: 54,
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 19,
  },
  bullets: { marginTop: 8, gap: 12 },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  checkWrap: {
    width: 25,
    height: 25,
    borderRadius: 100,
    backgroundColor: '#34C759',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  check: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  bulletText: {
    flex: 1,
    fontSize: 18,
    color: '#000000',
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 22,
  },
  footer: { paddingHorizontal: 25, paddingBottom: 20 },
  cta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: 315,
    height: 56,
    borderRadius: 28,
    shadowColor: 'rgba(76, 87, 255, 0.3)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 8,
  },
  ctaText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 24,
    marginRight: 8,
  },
  ctaArrow: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
})
