import { StyleSheet, Platform } from 'react-native'

const PURPLE = '#4f3be7'
const BG = '#FFFFFF'

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  statusBar: {
    height: Platform.OS === 'ios' ? 44 : 28,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeWrap: { backgroundColor: '#FF4D4F', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  time: { color: '#fff', fontWeight: '500', fontFamily: 'Inter', fontSize: 13 },
  statusIcons: { flexDirection: 'row' },
  icon: { marginLeft: 8, fontSize: 14 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 60 },
  progressWrap: { flex: 1, paddingRight: 16 },
  progressTrack: { height: 6, backgroundColor: '#EEE8FF', borderRadius: 6, overflow: 'hidden' },
  progressFill: { width: '88.88%', height: '100%', backgroundColor: PURPLE },
  content: { paddingHorizontal: 20, paddingTop: 18, flex: 1, alignItems: 'center' },
  context: {
    color: '#4f3be7',
    fontSize: 15,
    fontFamily: 'Inter',
    fontWeight: '500',
    lineHeight: 22,
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  title: { fontSize: 22, fontWeight: '500', color: '#111827', marginBottom: 6, fontFamily: 'Inter', alignSelf: 'flex-start' },
  gpaWrap: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  gpaButton: {
    width: 55.98,
    height: 55.98,
    borderRadius: 16,
    backgroundColor: '#d7dcff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gpaButtonText: {
    fontSize: 30,
    lineHeight: 36,
    color: PURPLE,
    fontFamily: 'Inter',
    fontWeight: '400',
  },
  gpaValueWrap: {
    width: 120,
    height: 48.01,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 15.99,
  },
  gpaValue: {
    fontSize: 48,
    lineHeight: 48,
    color: PURPLE,
    fontFamily: 'Inter',
    fontWeight: '400',
  },
  footer: { paddingHorizontal: 16, paddingBottom: 40 },
  cta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 12 },
  ctaText: { color: '#fff', fontSize: 16, fontWeight: '500', marginRight: 8 },
  ctaArrow: { color: '#fff', fontSize: 18, fontWeight: '500' },
  leftGradient: { position: 'absolute', left: -40, top: 80, width: 220, height: 420, borderRadius: 220, backgroundColor: '#F5EEFF', opacity: 0.7, transform: [{ rotate: '-25deg' }] },
  homeIndicator: { height: 6, backgroundColor: '#E9E9EF', marginHorizontal: 110, borderRadius: 3, marginTop: 10, marginBottom: Platform.OS === 'ios' ? 24 : 8 },
})
