import { StyleSheet, Platform } from 'react-native'

const PURPLE = '#7C3AED'
const BG = '#FFFFFF'

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  statusBar: {
    height: Platform.OS === 'ios' ? 44 : 28,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeWrap: { backgroundColor: '#FF4D4F', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  time: { color: '#fff', fontWeight: '700', fontFamily: 'Arimo', fontSize: 13 },
  statusIcons: { flexDirection: 'row' },
  icon: { marginLeft: 8, fontSize: 14 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 60 },
  back: { fontSize: 22, marginRight: 12 },
  progressWrap: { flex: 1, paddingRight: 16 },
  progressTrack: { height: 10, backgroundColor: '#F3EFFF', borderRadius: 6, overflow: 'hidden' },
  progressFill: { width: '92%', height: '100%', backgroundColor: PURPLE },
  scrollContent: { flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 24 },
  context: {
    color: '#7C3AED',
    fontSize: 15,
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 22,
    marginBottom: 8,
  },
  title: { fontSize: 22, fontWeight: '700', color: '#111827', marginBottom: 16, fontFamily: 'Arimo' },
  options: { marginTop: 6, gap: 12 },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingLeft: 19.99,
    height: 83.97,
    width: 320,
    borderRadius: 16,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
    marginBottom: 0,
  },
  optionSelected: { borderColor: PURPLE, backgroundColor: '#FBF7FF', borderWidth: 2 },
  iconContainer: {
    width: 43.98,
    height: 43.98,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15.99,
  },
  optionIcon: {
    fontSize: 24,
    lineHeight: 32,
    color: '#0A0A0A',
    fontFamily: 'Arimo',
  },
  optionLabel: {
    fontSize: 15,
    lineHeight: 22,
    color: '#000000',
    fontFamily: 'Arimo',
    fontWeight: '400',
  },
  footer: { paddingHorizontal: 25, paddingBottom: 20 },
  cta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', paddingVertical: 16, borderRadius: 12, borderWidth: 1, borderColor: '#E6E6F0' },
  ctaText: { color: '#111827', fontSize: 16, fontWeight: '700', marginRight: 8 },
  ctaArrow: { color: '#111827', fontSize: 18, fontWeight: '700' },
})
