import { StyleSheet, Platform } from 'react-native'

const PURPLE = '#7C3AED'
const BG = '#FFFFFF'

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 60 },
  progressWrap: { flex: 1, paddingRight: 16 },
  progressTrack: { height: 6, backgroundColor: '#EEE8FF', borderRadius: 6, overflow: 'hidden' },
  progressFill: { width: '100%', height: '100%', backgroundColor: '#7C3AED' },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    flex: 1,
    width: '100%'
  },
  context: {
    color: '#7C3AED',
    fontSize: 15,
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 22,
    marginBottom: 8,
    width: '100%',
  },
  title: {
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 25,
    marginBottom: 14,
    fontFamily: 'Arimo',
    color: '#000000',
    width: '100%',
  },
  options: { marginTop: 6, gap: 12 },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingLeft: 19.99,
    paddingRight: 19.99,
    paddingVertical: 0,
    gap: 15.99,
    width: '100%',
    height: 83.97,
    borderRadius: 16,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  optionSelected: {
    backgroundColor: '#FFFFFF',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 3,
  },
  optionIcon: {
    width: 43.98,
    height: 43.98,
    backgroundColor: '#DCFCE7',
    borderRadius: 16,
    fontSize: 24,
    lineHeight: 43.98,
    textAlign: 'center',
  },
  optionLabel: {
    fontSize: 15,
    fontFamily: 'Arimo',
    fontWeight: '400',
    lineHeight: 22,
    color: '#000000',
  },
  footer: { paddingHorizontal: 16, paddingBottom: 40 },
  continueWrap: { borderRadius: 100, overflow: 'hidden' },
  continueButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 100,
    paddingVertical: 0,
    paddingRight: 30,
    width: '100%',
    height: 55.98,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    flexDirection: 'row',
    marginBottom: 20,
  },
  continueText: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Arimo',
    lineHeight: 24,
    color: '#000000',
    textAlign: 'center',
  },
  gesture: { height: 6, backgroundColor: '#E9E9EF', marginHorizontal: 110, borderRadius: 3, marginTop: 10, marginBottom: Platform.OS === 'ios' ? 16 : 8 },
  optionOverride: { height: 70 },
})
