import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    marginTop: 47.5,
    marginHorizontal: 24,
    height: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressContainer: {
    flex: 1,
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 268435,
    overflow: 'hidden',
  },
  progressTrack: {
    width: '100%',
    height: '100%',
  },
  progressFill: {
    width: 150.5,
    height: 8,
    backgroundColor: '#9810FA',
    borderRadius: 268435,
  },
  mainQuestion: {
    marginHorizontal: 24,
    marginTop: 16,
    marginBottom: 16,
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Arimo',
    lineHeight: 32,
    color: '#0A0A0A',
  },
  optionsContainer: {
    marginHorizontal: 24,
    gap: 12,
    marginBottom: 100,
  },
  optionButton: {
    height: 61.6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 16,
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 0.8,
    borderColor: '#E5E7EB',
    borderRadius: 14,
  },
  optionButtonSelected: {
    borderColor: '#9810FA',
    borderWidth: 2,
  },
  optionIcon: {
    fontSize: 20,
    fontFamily: 'Arimo',
    fontWeight: '400',
    lineHeight: 28,
    color: '#0A0A0A',
    width: 27.46,
  },
  optionText: {
    fontSize: 16,
    fontFamily: 'Arimo',
    fontWeight: '400',
    lineHeight: 24,
    color: '#101828',
    flex: 1,
  },
  continueButton: {
    position: 'absolute',
    bottom: 30,
    left: 24,
    right: 24,
    height: 55.98,
    backgroundColor: '#FFFFFF',
    borderRadius: 49067700,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 3.2,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueButtonText: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Arimo',
    lineHeight: 24,
    color: '#000000',
  },
})
