import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 60 },
  progressWrap: { flex: 1, paddingRight: 16 },
  progressTrack: { height: 6, backgroundColor: '#EEE8FF', borderRadius: 6, overflow: 'hidden' },
  progressFill: { width: '75%', height: '100%', backgroundColor: '#7C3AED' },
  content: {
    paddingHorizontal: 28,
    paddingTop: 20,
    flex: 1,
    width: '100%'
  },
  contextText: {
    color: '#7C3AED',
    fontSize: 15,
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 22,
    marginBottom: 8,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: '700',
    fontFamily: 'Arimo',
    lineHeight: 40,
    letterSpacing: -0.64,
    color: '#0B0C10',
    marginBottom: 18,
  },
  cardContainer: {
    gap: 16,
    width: '100%',
    height: 207.6,
  },
  testimonialCard: {
    width: '100%',
    height: 195,
    backgroundColor: '#FFFFFF',
    borderWidth: 0.8,
    borderColor: '#EBEDF2',
    borderRadius: 24,
    shadowColor: '#4C57FF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  cardContent: {
    padding: 24.8,
    gap: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    height: 46,
    paddingRight: 24,
  },
  nameSection: {
    gap: 2,
    width: 170,
    height: 46,
  },
  cardName: {
    fontSize: 18,
    fontFamily: 'Arimo',
    fontWeight: '700',
    lineHeight: 24,
    color: '#0B0C10',
  },
  cardTitle: {
    fontSize: 14,
    fontFamily: 'Arimo',
    fontWeight: '400',
    lineHeight: 20,
    color: '#5A6171',
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
    width: 80,
    height: 16,
    marginRight: 20,
  },
  quote: {
    fontSize: 16,
    fontFamily: 'Arimo',
    fontWeight: '400',
    lineHeight: 24,
    color: '#0B0C10',
  },
  footer: {
    paddingHorizontal: 28,
    paddingBottom: 40,
  },
  continueButtonWrapper: {
    width: '100%',
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
  },
  continueButton: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4C57FF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 8,
  },
  continueButtonText: {
    fontSize: 17,
    fontWeight: '700',
    fontFamily: 'Arimo',
    lineHeight: 24,
    color: '#FFFFFF',
    marginRight: 8,
  },
  gestureBar: {
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    marginTop: 8,
    marginHorizontal: 120,
  },
})
