import { Dimensions, Platform, StyleSheet } from 'react-native'

const { height } = Dimensions.get('window')

export const welcomeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: Platform.OS === 'ios' ? 50 : 30,
    paddingHorizontal: 24,
    borderRadius: 0,
  },
  logoSection: {
    alignItems: 'center',
    marginTop: height * 0.08,
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostContainer: {
    width: 174,
    height: 174,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 11.8,
    elevation: 10,
  },
  logoImage: {
    width: 176,
    height: 176,
    borderRadius: 22,
  },
  headlineSection: {
    alignItems: 'center',
    marginTop: -height * 0.01,
  },
  headlineText: {
    fontFamily: 'Arimo',
    fontSize: 48,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -1.2,
    lineHeight: 48,
    textAlign: 'center',
  },
  headlineHighlight: {
    fontFamily: 'Arimo',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: -1.2,
    lineHeight: 48,
    textAlign: 'center',
  },
  gradientTextContainer: {
    borderRadius: 8,
  },
  featureTagsContainer: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingLeft: 20,
  },
  featureTag: {
    borderRadius: 9999,
    overflow: 'hidden',
    borderWidth: 0.8,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  featureTagInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10.8,
    paddingHorizontal: 10,
  },
  featureTagText: {
    fontFamily: 'Arimo',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  ctaSection: {
    width: '100%',
    alignItems: 'center',
    gap: 16,
    marginBottom: 16,
  },
  glassButton: {
    borderRadius: 9999,
    overflow: 'hidden',
    borderWidth: 0.8,
    borderColor: 'rgba(255, 223, 32, 0.3)',
  },
  glassButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10.8,
    paddingHorizontal: 20.8,
  },
  glassButtonText: {
    fontFamily: 'Arimo',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    textAlign: 'center',
    color: '#FEF9C2',
  },
  primaryButton: {
    width: '100%',
    height: 56,
    borderRadius: 34,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(139, 92, 246, 0.5)',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 40,
    elevation: 15,
  },
  primaryButtonGradient: {
    flex: 1,
  },
  primaryButtonOverlay: {
    flex: 1,
  },
  primaryButtonText: {
    fontFamily: 'Arimo',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    color: '#FFFFFF',
    zIndex: 1,
  },
  primaryButtonEmoji: {
    fontSize: 16,
    lineHeight: 24,
  },
  footer: {
    alignItems: 'center',
    width: '100%',
    marginBottom: 28,
    marginTop: -15,
  },
  footerText: {
    fontFamily: 'Arimo',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.7)',
  },
})

